### ISSUE TITLE
Account for new RDS TLS certificates

### ISSUE THREAD

**Issue by doublecompile** [libreworks/shady-island#122]
RDS issued new CA certificates and the underlying [mysql2](https://github.com/sidorares/node-mysql2) library we use for the `MysqlDatabase` construct [doesn't seem to support them yet](https://github.com/sidorares/node-mysql2/issues/2212).

Figure out a workaround while that library is working on a fix.

**Comment by bdf-app-mgmt** [comment]
I found a workaround (i don't like it but i need a working application), you should download the certificate from https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem and then use it in the configuration:
```
{
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  waitForConnections: true,
  connectionLimit: 10,
  connectTimeout: 10000,
  queueLimit: 0,
  debug: false,
  ssl: {
            ca: readFileSync('src/config/global-bundle.pem'),
         }
 }
```
  Before the ca change my configuration was:
```
{
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  waitForConnections: true,
  connectionLimit: 10,
  connectTimeout: 10000,
  queueLimit: 0,
  debug: false,
  ssl: 'Amazon RDS'
}
```
